# Generated by Django 3.2 on 2022-03-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('department_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('facility_emplpoyees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility'),
        ),
    ]
