# Generated by Django 3.2 on 2022-03-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='facility_emplpoyees',
        ),
    ]
