# Generated by Django 3.2 on 2022-03-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employees_facility_emplpoyees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Facility',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='facility',
            new_name='faculty',
        ),
    ]
