# Generated by Django 4.0.3 on 2022-03-29 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220322_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='office_place',
            field=models.CharField(default='ds', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
