# Generated by Django 4.0.3 on 2022-04-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
