# Generated by Django 3.2 on 2022-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_place',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_dean',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_info',
            field=models.TextField(default='unknown'),
        ),
    ]
