# Generated by Django 4.0.3 on 2022-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220506_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_place',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
