# Generated by Django 4.0.3 on 2022-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_office_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_imge', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
