# Generated by Django 4.0.3 on 2022-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_faculty_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty_Image',
        ),
        migrations.AddField(
            model_name='faculty',
            name='established_date',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
