# Generated by Django 4.0.3 on 2022-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_faculty_image_faculty_established_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='established_date',
            field=models.IntegerField(default=2000),
        ),
    ]
