# Generated by Django 4.0.3 on 2022-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_employee_office_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_place',
            field=models.CharField(max_length=50),
        ),
    ]
