# Generated by Django 4.0.3 on 2022-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_employee_office_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
